export const contactInfo = {
  firstName: "Remco",
  lastName: "Stoeten",
  fullName: "Remco Stoeten",
  handle: "@remcostoeten",
  city: "Lemmer, Friesland",
  country: "The Netherlands",
  email: process.env.NEXT_PUBLIC_EMAIL,
  gmail: process.env.NEXT_PUBLIC_GMAIL,
  phone: process.env.NEXT_PUBLIC_PHONE,
  linkedin: "https://www.linkedin.com/in/remco-stoeten/",
  linkedinhandle: "in/remco-stoeten",
  github: "https://github.com/remcostoeten",
  gitlab: "https://gitlab.com/remcostoeten",
  baseURL: "https://remcostoeten.com",
};
