'use client'
import Head from "next/head";
import { FcGoogle } from "react-icons/fc";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { HiOutlineClipboardList } from "react-icons/hi";
import { getAuth, signInWithRedirect, GoogleAuthProvider, signOut } from 'firebase/auth';
import { useAuthState } from 'react-firebase-hooks/auth';
import { auth } from "@/core/lib/firebase"



const useRedirect = () => {
  const router = useRouter();
  const [user, loading] = useAuthState(auth);
  const [justLoggedIn, setJustLoggedIn] = useState(false);

  useEffect(() => {
    if (!loading && user && !justLoggedIn) {
      setJustLoggedIn(true);
      router.push("/projects");
    }
  }, [loading, user]);

  useEffect(() => {
    router.prefetch("/projects");
  }, []);
};

export default function Home() {
  useRedirect();
  const [user, loading, error] = useAuthState(auth);

  if (loading) {
    return <p>Initialising User...</p>;
  }


  return (
    <>
      <Head>
        <title>Kanban</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto mt-32 flex flex-col items-center">
        <HiOutlineClipboardList className="text-primary-500 text-9xl" />
        <h3 className="text-xl font-semibold">Welcome Kanban!</h3>
        <h4 className="text-center text-lg">
          It is a project management tool designed to help visualize work, limit
          work-in-progress, and maximize efficiency or flow
        </h4>
        {user ? (
          <button onClick={() => signOut(auth)} className="mb-2 mt-10 w-80 rounded bg-blue-500 text-white">
            Log out
          </button>
        ) : (
          <button onClick={() => signInWithRedirect(auth, new GoogleAuthProvider())} className="mb-2 mt-10 w-80 rounded bg-blue-500 text-white">
            <div className="flex items-center justify-center">
              <FcGoogle className="mr-2" />
              Continue with Google
            </div>
          </button>
        )}
        <p className="opacity-60">
          Secured by{" "}
          <a
            className="text-inherit underline"
            href="https://firebase.google.com/"
          >
            Firebase
          </a>
        </p>
      </div>
    </>
  );
}