import { useEffect } from "react"
import Head from "next/head"
import { useRouter } from "next/router"
import { Button, Typography, theme } from "antd"
import { User } from "firebase/auth"
import { FcGoogle } from "react-icons/fc"
import { HiOutlineClipboardList } from "react-icons/hi"
import { useAuth } from "@/core/lib/database/auth"
import { signIn } from "@/core/lib/database/google"


const { Title, Text } = Typography

/**
 * redirect if user has logged in
 */
const useRedirect = () => {
  const router = useRouter()
  const { user, loading } = useAuth() as { user: User | null; loading: boolean }

  useEffect(() => {
    if (!loading && user) {
      router.push("/projects")
    }
  }, [loading, user, router])

  useEffect(() => {
    router.prefetch("/projects")
  }, [router])

  return (
    <>
      <Head>
        <title>Kanban</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto mt-32 flex flex-col items-center">
        <HiOutlineClipboardList className="text-9xl" />
        <Title level={3}>Welcome Kanban!</Title>
        <Title level={4} className="text-center">
          It is a project management tool designed to help visualize work, limit
          work-in-progress, and maximize efficiency or flow
        </Title>
        <Button onClick={signIn} className="mb-2 mt-10 w-80">
          <div className="flex items-center justify-center">
            <FcGoogle className="mr-2" />
            Continue with Google
          </div>
        </Button>
        <Text className="opacity-60">
          Secured by{" "}
          <a
            className="!text-inherit !underline"
            href="https://firebase.google.com/"
          >
            Firebase
          </a>
        </Text>
      </div>
    </>
  )
}

export default useRedirect
